### ISSUE TITLE
spinner keeps on showing

### ISSUE THREAD

**Issue by TheOverLordKotan** [ridlafadilah/do-ngx#5]
🐞 bug report
Affected Package
I think, The issue is caused by package @dongkap/do-auth

Is this a regression?
Not sure 

Description
The problem is show when the app startup and you see the explorer **http://localhost:4242/** show the next error:
" Error: Uncaught (in promise): NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found."

When the 'AppComponent' call 'this.settingsIndexedDB.get('locale')'.
I comment this line and the next behavior its the nb-global-spinner doesnt hide

![image](https://user-images.githubusercontent.com/29128223/97124853-d15df780-16ff-11eb-8aed-7b75f4da0b13.png)

Is this behaviour expected? If so is there another way to fail the test when such an error is thrown?
I expected see the login for from @dongkap/do-auth but I only saw the spinner global 

🔬 Minimal Reproduction

Just run npm run start:do-ngx

🔥 Exception or Error

" Error: Uncaught (in promise): NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
Error: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found."
🌍 Your Environment
dongkap: 
dongkap:  #0.0.0
- [ ]  @ridlafadilah 

```
      _                           _                    
   __| |   ___    _ __     __ _  | | __   __ _   _ __  
  / _` |  / _ \  | '_ \   / _` | | |/ /  / _` | | '_ \ 
 | (_| | | (_) | | | | | | (_| | |   <  | (_| | | |_) |
  \__,_|  \___/  |_| |_|  \__, | |_|\_\  \__,_| | .__/ 
                          |___/                 |_|    

```
Angular CLI: 10.1.2
Node: 12.18.3
OS: win x64
Angular: 10.1.2

Package                             Version
-------------------------------------------------------------
@angular-devkit/core                10.1.2
@angular-devkit/schematics         10.1.2
@angular/animations                 10.1.2
@angular/cli                        10.1.2
@angular/common                     10.1.2
@angular/compiler                   10.1.2
@angular/compiler-cli               10.1.2
@angular/forms                      10.1.2
@angular/platform-browser           10.1.2
@angular/platform-browser-dynamic   10.1.2
@angular/router                     10.1.2
rxjs                                6.6.2
typescript                          3.9.7
Anything else relevant?
No.

**Comment by ridlafadilah** [comment]
Hi @TheOverLordKotan , thanks for the feedback.
I found the problem, the store object in indexedDB is not formed.

**Comment by TheOverLordKotan** [comment]
Thank you! I dont kwon if it was the problem, but I removed the IndexStore on the explorer and I can login. **Good work Master**!
